openapi: 3.0.0
info:
  title: Physna Public ClientCredentials API
  version: 2.0.1
  contact:
    name: Support
    email: support@physna.com
servers:
- url: /v2
tags:
- name: ClientCredentials
paths:
  /client-credentials:
    post:
      operationId: CreateClientCredentials
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleClientCredentialsResponse'
        '409':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: Create Client Credentials. These are used for programmatic access (service-to-service communication) to the API.
      tags:
      - ClientCredentials
      security:
      - okta:
        - Administrators
        - Authors
        - Viewers
      parameters:
      - in: header
        name: X-PHYSNA-TENANTID
        required: false
        schema:
          type: string
    get:
      operationId: GetClientCredentials
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleClientCredentialsIDResponse'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: Get Client Credentials.
      tags:
      - ClientCredentials
      security:
      - okta:
        - Administrators
        - Authors
        - Viewers
      parameters:
      - in: header
        name: X-PHYSNA-TENANTID
        required: false
        schema:
          type: string
  /client-credentials/{clientId}:
    delete:
      operationId: DeleteClientCredentials
      responses:
        '204':
          description: No content
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: Delete Client Credentials.
      tags:
      - ClientCredentials
      security:
      - okta:
        - Administrators
        - Authors
        - Viewers
      parameters:
      - in: path
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: X-PHYSNA-TENANTID
        required: false
        schema:
          type: string
components:
  schemas:
    ClientCredentials:
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
      required:
      - clientId
      - clientSecret
      type: object
      additionalProperties: false
    ErrorResponse:
      properties:
        error:
          properties:
            message:
              type: string
          required:
          - message
          type: object
      required:
      - error
      type: object
      additionalProperties: false
    SingleClientCredentialsResponse:
      properties:
        clientCredentials:
          $ref: '#/components/schemas/ClientCredentials'
      required:
      - clientCredentials
      type: object
      additionalProperties: false
    SingleClientCredentialsIDResponse:
      properties:
        clientId:
          type: string
      required:
      - clientId
      type: object
      additionalProperties: false
  securitySchemes:
    okta:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://physna.okta.com/oauth2/default/v1/token
          authorizationUrl: https://physna.okta.com/oauth2/default/v1/authorize
          scopes:
            openid: ''
            tenant: ''
            roles: ''
externalDocs:
  description: Public Api Guide
  url: https://physna.github.io/public-api-guide/
